version: '3'
services:
  db:
    image: postgres:15.3
    container_name: fr_db
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
    command: /app/app
    container_name: fr_app
    depends_on:
      - db
