version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TIMEZONE}
    ports:
      - "${DB_PORT}:5432"